name: Kwiki-UserName-Auth
version: 0.10
abstract: Online user regsitration plugin for Kwiki.
author: Kang-min Liu <gugod@gugod.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  Kwiki: 0.38
  Kwiki::DB: 0
  Kwiki::Session: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
